services:
  db:
    image: postgres:alpine
    container_name: hexagone_db
    environment:
      POSTGRES_DB: hexagone
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
